### ISSUE TITLE
用.info指令时会报错java.lang.NullPointerException

### ISSUE THREAD

**Issue by wdnmd23333fdhsuidus** [StageGuard/OsuMapSuggester#11]
![L0QRD7M 1UBOJP0~2KK F5G](https://user-images.githubusercontent.com/81455657/205455230-92d12bcf-344f-48ea-902e-326f60c6f6c7.png)

**Comment by StageGuard** [comment]
是bg模糊的问题，暂时的解决方法是设置模糊类型为不模糊
`.info set t=2`

**Comment by wdnmd23333fdhsuidus** [comment]
还是报错NullPointer




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "StageGuard/OsuMapSuggester"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月4日(星期天) 晚上9:21
***@***.***&gt;;
抄送:&nbsp;"Away From ***@***.******@***.***&gt;;
主题:&nbsp;Re: [StageGuard/OsuMapSuggester] 用.info指令时会报错java.lang.NullPointerException (Issue #11)





 
是bg模糊的问题，暂时的解决方法是设置模糊类型为不模糊
 .info set t=2

**Comment by StageGuard** [comment]
```
2022-12-04 14:25:48 E/OsuMapSuggester: java.lang.NullPointerException                                                               
java.lang.NullPointerException                                                                                                      
        at OsuMapSuggester-linux-x64-2.5.2.mirai2.jar//me.stageguard.obms.graph.item.Profile.drawBestPerformanceItem(Profile.kt:487)
        at OsuMapSuggester-linux-x64-2.5.2.mirai2.jar//me.stageguard.obms.graph.item.Profile.drawBestPerformanceCard(Profile.kt:334)
        at OsuMapSuggester-linux-x64-2.5.2.mirai2.jar//me.stageguard.obms.graph.item.Profile.drawProfilePanelImpl(Profile.kt:264)
        at OsuMapSuggester-linux-x64-2.5.2.mirai2.jar//me.stageguard.obms.graph.item.Profile.drawProfilePanel(Profile.kt:98)
        at OsuMapSuggester-linux-x64-2.5.2.mirai2.jar//me.stageguard.obms.graph.item.Profile$drawProfilePanel$1.invokeSuspend(Profil
e.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
