### ISSUE TITLE
Java.util.NoSuchElementException: List is empty.

### ISSUE THREAD

**Issue by Zijun9297** [StageGuard/OsuMapSuggester#16]
发生了未知错误，请访问 github.com/StageGuard/OsuMapSuggester/issues 并提交以下错误：
java.util.NoSuchElementException: List is empty.

**Comment by StageGuard** [comment]
提供控制台的完整错误日志

**Comment by Zijun9297** [comment]
感谢作者大大的回复
![image](https://github.com/StageGuard/OsuMapSuggester/assets/73068096/e694abc4-d00d-4c3a-b4f6-b4ba9c91ebb4)

**Comment by StageGuard** [comment]
查询的用户有 std 模式最佳成绩吗？

**Comment by Zijun9297** [comment]
有的，
查询.rep指令的时候提示的是：请求 osu!api 时出现错误，请重试。
之前很长时间能稳定使用所有功能，但是突然之间所有功能都报错了
重启mirai和服务器，检查网络都没能解决
![image](https://github.com/StageGuard/OsuMapSuggester/assets/73068096/c9abe46e-957f-47de-b009-cba56140889d)

**Comment by StageGuard** [comment]
> 有的， 查询.rep指令的时候提示的是：请求 osu!api 时出现错误，请重试。 之前很长时间能稳定使用所有功能，但是突然之间所有功能都报错了 重启mirai和服务器，检查网络都没能解决 ![image](https://private-user-images.githubusercontent.com/73068096/302049916-c9abe46e-957f-47de-b009-cba56140889d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5ODEzMjUsIm5iZiI6MTcwNjk4MTAyNSwicGF0aCI6Ii83MzA2ODA5Ni8zMDIwNDk5MTYtYzlhYmU0NmUtOTU3Zi00N2RlLWIwMDktY2JhNTYxNDA4ODlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDE3MjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYzg1MjFiYmY4Y2I5NTA3NDZlMWFiOWMyYTZmYTMyMzUwYjM3Y2QzNjhlY2I1ODc1OTZlMTZkMTdkOTg5MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cJzkEYzqHnGtp1b3XqmqJvsfhyb2VKntdOrpJcdIN7U)

日志没有发完整，可以复制到 issue 里而不是发图片。猜测可能是最近 lazer 转正的缘故，osu api 可能发生了变化

**Comment by Zijun9297** [comment]
抱歉，不是很会使用github的功能，只是最近在辅助别人组织osu比赛，用不了有点可惜，来这里联系一下
日志：
`2024-02-04 02:09:43 V/Bot.227554127: [[9297的工作室]<$ǿĀD>(784282422)] 子君9297(2433380978) -> .rep
2024-02-04 02:09:43 I/OsuMapSuggester: GET: https://osu.ppy.sh/api/v2/users/8647217/scores/recent?mode=osu&include_fails=1&limit=1&offset=0
2024-02-04 02:09:43 I/OsuMapSuggester: GET: https://osu.ppy.sh/api/v2/users/8647217/scores/recent?mode=osu&include_fails=1&limit=1&offset=1
2024-02-04 02:09:43 I/OsuMapSuggester: GET: https://osu.ppy.sh/api/v2/users/8647217/scores/recent?mode=osu&include_fails=1&limit=1&offset=2
2024-02-04 02:09:44 I/OsuMapSuggester: GET: https://osu.ppy.sh/api/v2/users/8647217/scores/recent?mode=osu&include_fails=1&limit=1&offset=3
2024-02-04 02:09:44 I/OsuMapSuggester: GET: https://osu.ppy.sh/api/v2/users/8647217/scores/recent?mode=osu&include_fails=1&limit=1&offset=4
2024-02-04 02:09:44 E/OsuMapSuggester: me.stageguard.obms.BadResponseException: Bad respond for requesting https://osu.ppy.sh/api/v2/users/8647217/scores/recent, respond text: [{"accuracy":0.8217535153019024,"best_id":4578721020,"created_at":"2024-02-02T16:09:19Z","id":4578721020,"max_combo":233,"mode":"osu","mode_int":0,"mods":[],"passed":true,"perfect":false,"pp":11.5372,"rank":"C","replay":true,"score":1144280,"statistics":{"count_100":75,"count_300":303,"count_50":19,"count_geki":null,"count_katu":null,"count_miss":6},"type":"score_best_osu","user_id":8647217,"current_user_attributes":{"pin":{"is_pinned":false,"score_id":2277674757,"score_type":"solo_score"}},"beatmap":{"beatmapset_id":1731654,"difficulty_rating":4.36,"id":3786943,"mode":"osu","status":"ranked","total_length":130,"user_id":11839745,"version":"Hyper","accuracy":7,"ar":8.3,"bpm":180,"convert":false,"count_circles":181,"count_sliders":219,"count_spinners":3,"cs":3.6,"deleted_at":null,"drain":5,"hit_length":118,"is_scoreable":true,"last_updated":"2022-12-31T04:12:55Z","mode_int":0,"passcount":3007,"playcount":12439,"ranked":1,"url":"https:\/\/osu.ppy.sh\/beatmaps\/3786943","checksum":"d062ded6a5a06e2c62ca630897f087e4"},"beatmapset":{"artist":"Maozon","artist_unicode":"Maozon","covers":{"cover":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/cover.jpg?1672459989","cover@2x":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/cover@2x.jpg?1672459989","card":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/card.jpg?1672459989","card@2x":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/card@2x.jpg?1672459989","list":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/list.jpg?1672459989","list@2x":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/list@2x.jpg?1672459989","slimcover":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/slimcover.jpg?1672459989","slimcover@2x":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/slimcover@2x.jpg?1672459989"},"creator":"VoiceCore","favourite_count":114,"hype":null,"id":1731654,"nsfw":false,"offset":0,"play_count":67101,"preview_url":"\/\/b.ppy.sh\/preview\/1731654.mp3","source":"Lanota","spotlight":false,"status":"ranked","title":"Stasis","title_unicode":"Stasis","track_id":null,"user_id":11839745,"video":false},"user":{"avatar_url":"https:\/\/a.ppy.sh\/8647217?1669222586.jpeg","country_code":"CN","default_group":"default","id":8647217,"is_active":true,"is_bot":false,"is_deleted":false,"is_online":false,"is_supporter":false,"last_visit":"2024-02-03T14:19:27+00:00","pm_friends_only":false,"profile_colour":null,"username":"Zijun9297"}}]
me.stageguard.obms.BadResponseException: Bad respond for requesting https://osu.ppy.sh/api/v2/users/8647217/scores/recent, respond text: [{"accuracy":0.8217535153019024,"best_id":4578721020,"created_at":"2024-02-02T16:09:19Z","id":4578721020,"max_combo":233,"mode":"osu","mode_int":0,"mods":[],"passed":true,"perfect":false,"pp":11.5372,"rank":"C","replay":true,"score":1144280,"statistics":{"count_100":75,"count_300":303,"count_50":19,"count_geki":null,"count_katu":null,"count_miss":6},"type":"score_best_osu","user_id":8647217,"current_user_attributes":{"pin":{"is_pinned":false,"score_id":2277674757,"score_type":"solo_score"}},"beatmap":{"beatmapset_id":1731654,"difficulty_rating":4.36,"id":3786943,"mode":"osu","status":"ranked","total_length":130,"user_id":11839745,"version":"Hyper","accuracy":7,"ar":8.3,"bpm":180,"convert":false,"count_circles":181,"count_sliders":219,"count_spinners":3,"cs":3.6,"deleted_at":null,"drain":5,"hit_length":118,"is_scoreable":true,"last_updated":"2022-12-31T04:12:55Z","mode_int":0,"passcount":3007,"playcount":12439,"ranked":1,"url":"https:\/\/osu.ppy.sh\/beatmaps\/3786943","checksum":"d062ded6a5a06e2c62ca630897f087e4"},"beatmapset":{"artist":"Maozon","artist_unicode":"Maozon","covers":{"cover":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/cover.jpg?1672459989","cover@2x":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/cover@2x.jpg?1672459989","card":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/card.jpg?1672459989","card@2x":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/card@2x.jpg?1672459989","list":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/list.jpg?1672459989","list@2x":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/list@2x.jpg?1672459989","slimcover":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/slimcover.jpg?1672459989","slimcover@2x":"https:\/\/assets.ppy.sh\/beatmaps\/1731654\/covers\/slimcover@2x.jpg?1672459989"},"creator":"VoiceCore","favourite_count":114,"hype":null,"id":1731654,"nsfw":false,"offset":0,"play_count":67101,"preview_url":"\/\/b.ppy.sh\/preview\/1731654.mp3","source":"Lanota","spotlight":false,"status":"ranked","title":"Stasis","title_unicode":"Stasis","track_id":null,"user_id":11839745,"video":false},"user":{"avatar_url":"https:\/\/a.ppy.sh\/8647217?1669222586.jpeg","country_code":"CN","default_group":"default","id":8647217,"is_active":true,"is_bot":false,"is_deleted":false,"is_online":false,"is_supporter":false,"last_visit":"2024-02-03T14:19:27+00:00","pm_friends_only":false,"profile_colour":null,"username":"Zijun9297"}}]
        at OsuMapSuggester-windows-x64-2.5.2.mirai2.jar//me.stageguard.obms.osu.api.OsuWebApi$userScore$getTailrec$$inlined$get$2.invokeSuspend(OsuWebApi.kt:411)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 324: Unexpected symbol 'n' in numeric literal at path: $.array[0].statistics.count_geki
JSON input: .....03,"count_50":19,"count_geki":null,"count_katu":null,"count_.....
                at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
                at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
                at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:584)
                at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:582)
                at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeNumericLiteral(AbstractJsonLexer.kt:620)
                at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeInt(StreamingJsonDecoder.kt:300)
                at kotlinx.serialization.encoding.AbstractDecoder.decodeIntElement(AbstractDecoder.kt:53)
                at OsuMapSuggester-windows-x64-2.5.2.mirai2.jar//me.stageguard.obms.osu.api.dto.ScoreStatisticsDTO$$serializer.deserialize(ScoreDTO.kt:177)
                at OsuMapSuggester-windows-x64-2.5.2.mirai2.jar//me.stageguard.obms.osu.api.dto.ScoreStatisticsDTO$$serializer.deserialize(ScoreDTO.kt:177)
                at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
                at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
                at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:162)
                at OsuMapSuggester-windows-x64-2.5.2.mirai2.jar//me.stageguard.obms.osu.api.dto.ScoreDTO$$serializer.deserialize(ScoreDTO.kt:15)
                at OsuMapSuggester-windows-x64-2.5.2.mirai2.jar//me.stageguard.obms.osu.api.dto.ScoreDTO$$serializer.deserialize(ScoreDTO.kt:15)
                at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
                at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
                at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:162)
                at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:533)
                at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
                at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
                at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
                at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
                at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
                at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
                at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
                at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:162)
                at OsuMapSuggester-windows-x64-2.5.2.mirai2.jar//me.stageguard.obms.osu.api.ArrayResponseWrapper$$serializer.deserialize(OsuWebApi.kt:371)
                at OsuMapSuggester-windows-x64-2.5.2.mirai2.jar//me.stageguard.obms.osu.api.ArrayResponseWrapper$$serializer.deserialize(OsuWebApi.kt:371)
                at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
                at kotlinx.serialization.json.Json.decodeFromString(Json.kt:97)
                at OsuMapSuggester-windows-x64-2.5.2.mirai2.jar//me.stageguard.obms.osu.api.OsuWebApi$userScore$getTailrec$$inlined$get$2.invokeSuspend(OsuWebApi.kt:400)
                ... 8 more

2024-02-04 02:09:45 V/Bot.227554127: Group(784282422) <- [mirai:at:2433380978] 请求 osu!api 时出现错误，请重试。`

**Comment by Zijun9297** [comment]
作者您好，请问还打算修复吗，已经完全不能正常使用了QAQ

**Comment by StageGuard** [comment]
> 作者您好，请问还打算修复吗，已经完全不能正常使用了QAQ

实在是没有时间处理。。
