### ISSUE TITLE
.skill查询异常(Beatmap stack leniency is invalid)

### ISSUE THREAD

**Issue by SleepyAsh0191** [StageGuard/OsuMapSuggester#5]
发起查询的玩家：
[RandomEnch](https://osu.ppy.sh/users/16605104)

错误日志：

```
2021-10-16 18:55:18 I/OsuMapSuggester: POST: https://osu.ppy.sh/oauth/token
2021-10-16 18:55:20 I/OsuMapSuggester: GET: https://osu.ppy.sh/api/v2/users/16605104/scores/best?mode=osu&include_fails=0&limit=50&offset=0
2021-10-16 18:55:20 I/OsuMapSuggester: GET: https://osu.ppy.sh/api/v2/users/16605104/scores/best?mode=osu&include_fails=0&limit=50&offset=50
2021-10-16 18:55:20 I/OsuMapSuggester: GET: https://old.ppy.sh/osu/1145
2021-10-16 18:55:21 I/OsuMapSuggester: GET: https://old.ppy.sh/osu/1145
2021-10-16 18:55:21 E/OsuMapSuggester: java.lang.IllegalStateException: BEATMAP_PARSE_ERROR:java.lang.IllegalArgumentException: Beatmap stack leniency is invalid.
java.lang.IllegalStateException: BEATMAP_PARSE_ERROR:java.lang.IllegalArgumentException: Beatmap stack leniency is invalid.
        at me.stageguard.obms.cache.BeatmapCache.getBeatmap(BeatmapCache.kt:47)
        at me.stageguard.obms.cache.BeatmapCache$getBeatmap$1.invokeSuspend(BeatmapCache.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)

2021-10-16 18:55:22 V/Bot.779008220: Group(432995268) <- [mirai:at:1048421623] 解析 Beatmap 1145 时发生了异常: unhandled exception: BEATMAP_PARSE_ERROR:java.lang.IllegalArgumentException: Beatmap stack leniency is invalid.
```

别问我为什么这个beatmap ID为什么是这么臭，我不知道

**Comment by StageGuard** [comment]
push了
