### ISSUE TITLE
OsuMapSuggester: Unhandled: GET - /authCallback

### ISSUE THREAD

**Issue by MeiJuice** [StageGuard/OsuMapSuggester#8]
2022-07-10 17:42:23 E/OsuMapSuggester: Unhandled: GET - /authCallback
java.lang.LinkageError: loader constraint violation: when resolving method 'void io.ktor.client.request.HttpRequestBuilder.setMethod(io.ktor.http.HttpMethod)' the class loader 'OsuMapSuggester-2.3.0.mirai.jar' @5d497a91 of the current class, me/stageguard/obms/osu/api/OsuWebApi$getTokenWithCode$$inlined$postImpl$1, and the class loader 'app' for the method's defining class, io/ktor/client/request/HttpRequestBuilder, have different Class objects for the type io/ktor/http/HttpMethod used in the signature (me.stageguard.obms.osu.api.OsuWebApi$getTokenWithCode$$inlined$postImpl$1 is in unnamed module of loader 'OsuMapSuggester-2.3.0.mirai.jar' @5d497a91, parent loader 'global-shared' @636bbbbb; io.ktor.client.request.HttpRequestBuilder is in unnamed module of loader 'app')
        at OsuMapSuggester-2.3.0.mirai.jar//me.stageguard.obms.osu.api.OsuWebApi$getTokenWithCode$$inlined$postImpl$1.invokeSuspend(OsuWebApi.kt:382)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by StageGuard** [comment]
应该是用的最新版本 mirai 吧，目前还不支持最新版 mirai。一会我更新一下依赖

**Comment by MeiJuice** [comment]
那当时开发用的是哪个版本的mirai，我用旧版本试一下

**Comment by StageGuard** [comment]
> 那当时开发用的是哪个版本的mirai，我用旧版本试一下

2.9.1

**Comment by MeiJuice** [comment]
可以的话适配一下新版本的mcl吧，试过老版本也是同样的错误。进入屙屎授权认证并且点击了同意之后，网页500加上面的报错。看看怎么解决这个问题。谢谢。

**Comment by StageGuard** [comment]
已解决，下载最新 release 即可
