### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: /tmp/skija_0.92.15/libskija.so: libGL.so.1: 无法打开共享对象文件: 没有那个文件或目录

### ISSUE THREAD

**Issue by MeiJuice** [StageGuard/OsuMapSuggester#9]
> java.lang.UnsatisfiedLinkError: /tmp/skija_0.92.15/libskija.so: libGL.so.1: 无法打开共享对象文件: 没有那个文件或目录
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.load0(Unknown Source)
        at java.base/java.lang.System.load(Unknown Source)
        at OsuMapSuggester-2.4.0.mirai.jar//org.jetbrains.skija.impl.Library.load(Library.java:77)
        at OsuMapSuggester-2.4.0.mirai.jar//org.jetbrains.skija.impl.Library.staticLoad(Library.java:47)
        at OsuMapSuggester-2.4.0.mirai.jar//org.jetbrains.skija.Surface.<clinit>(Surface.java:9)
        at OsuMapSuggester-2.4.0.mirai.jar//me.stageguard.obms.graph.item.BestPerformanceDetail.drawBestPerformancesImage(BestPerformanceDetail.kt:48)
        at OsuMapSuggester-2.4.0.mirai.jar//me.stageguard.obms.bot.route.BestPerformanceAnalyzeKt$processOrderResultAndSend$bytes$1.invokeSuspend(bestPerformanceAnalyze.kt:191)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by LaoLittle** [comment]
百度安装OpenGL
